# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
School.create(name:'Chintadripet Boys Higher Secondary School',location:'Chintadripet',city:'chennai')
School.create(name:'Guru Nanak Mat.Hr.Sec School',location:'Velachery',city:'chennai')
School.create(name:'K.C.Sankaralinga Nadar higher Secondary School',location:'Old Washermanpet',city:'chennai')
School.create(name:'GTA Vidhya Mandir',location:'Neelankarai',city:'chennai')
School.create(name:'GT Vidhya Mandir',location:'Thiruvallur District',city:'chennai')
School.create(name:'Chennai Public School',location:'Thirumazhisai and Anna Nagar',city:'chennai')
School.create(name:'CPS Global School',location:'Thirumazhisai and Anna Nagar',city:'chennai')
School.create(name:'Adarsh Vidyalaya',location:'Royapettah',city:'chennai')
School.create(name:'Akshar Arbol International School',location:'West Mambalam, T.Nagar',city:'chennai')
School.create(name:'Holy Cross Matriculation School Chennai',location:'Thiruvottiyur',city:'chennai')
School.create(name:'Sri Sankara Global Cambridge International School',location:'Pammal',city:'chennai')
School.create(name:'American International School Chennai',location:'Tharamani',city:'chennai')
School.create(name:'AMM Matriculation Higher Secondary School',location:'Kotturpuram',city:'chennai')
School.create(name:'Asan Memorial Senior Secondary School',location:'Thousand Lights',city:'chennai')
School.create(name:'Babaji Vidhyashram',location:'Sholinganallur, OMR IT - Highway',city:'chennai')
School.create(name:'Bentinck School, Vepery',location:'Vepery',city:'chennai')
School.create(name:'Bharath senior secondary school',location:'121, Kamaraj Avenue, Adyar',city:'chennai')
School.create(name:'Chettinad Vidyashram',location:'R. A. Puram',city:'chennai')
School.create(name:'Chinmaya Vidyalaya',location:'Anna Nagar, Virugambakkam, Taylors Road',city:'chennai')
School.create(name:'Campus K',location:'Sholinganallur',city:'chennai')
School.create(name:'Sri Ram Dayal Khemka Vivekananda Vidyalaya Junior College',location:'Thiruvottiyur',city:'chennai')
School.create(name:'Smt. Ramkuwar Devi Fomra Vivekananda Vidyalaya',location:'Chromepet',city:'chennai')
School.create(name:'Dr.Nalli Kuppuswami Vivekananda Vidyalaya Junior College',location:'Korattur',city:'chennai')
School.create(name:'C.S.I. Bain Matriculation Higher Secondary School',location:'Kilpauk',city:'chennai')
School.create(name:'C.S.I. Ewart Matriculation Higher Secondary School',location:'Purasawalkam',city:'chennai')
School.create(name:'D.A.V. Boys Senior Secondary School',location:'Gopalapuram',city:'chennai')
School.create(name:'D.A.V. Public School',location:'Cenotaph Road, Teynampet',city:'chennai')
School.create(name:'Daniel Matriculation Higher Secondary School',location:'Korukkupet',city:'chennai')
School.create(name:'Dawn School',location:'Nolambur',city:'chennai')
School.create(name:'Don Bosco Matriculation Higher Secondary School',location:'Egmore',city:'chennai')
School.create(name:'Doveton Corrie Boys Higher Secondary School',location:'Vepery',city:'chennai')
School.create(name:'Gill Adarsh Matriculation Higher Secondary School',location:'Royapettah',city:'chennai')
School.create(name:'G. K. Shetty Vivekananda Vidyalaya',location:'Ambattur',city:'chennai')
School.create(name:'German International School of Chennai',location:'Neelankarai',city:'chennai')
School.create(name:'Good Earth School',location:'Manimangalam',city:'chennai')
School.create(name:'HLC International',location:'Old Mahabalipuram Road',city:'chennai')
School.create(name:'Kalaimagal Viddyalaya Matriculation Higher Secondary School',location:'Royapuram',city:'chennai')
School.create(name:'Holy Angels Anglo Indian Higher Secondary School',location:'T Nagar',city:'chennai')
School.create(name:'KC High School',location:'Kotturpuram',city:'chennai')
School.create(name:'Khivraj Olympia School',location:'Thiruneermalai',city:'chennai')
School.create(name:'SAN ACADEMY CBSE School',location:'PALLIKARANAI',city:'chennai')
School.create(name:'Kendriya Vidyalaya Senior Sec. School',location:'CLRI Campus',city:'chennai')
School.create(name:'Kendriya Vidyalaya Senior Sec. School',location:'IIT Madras',city:'chennai')
School.create(name:'Loyola Matriculation Higher Secondary School',location:'Kodambakkam',city:'chennai')
School.create(name:'Maharishi Vidya Mandir',location:'Chetput',city:'chennai')
School.create(name:'MCTM International School',location:'Chennai',city:'chennai')
School.create(name:'Muslim Higher Secondary School',location:'Triplicane',city:'chennai')
School.create(name:'New Prince Matriculation Higher Secondary School',location:'',city:'chennai')
School.create(name:'Pon Vidyashram',location:'Valasaravakkam',city:'chennai')
School.create(name:'Prince Matriculation Higher Secondary School',location:'Madipakkam',city:'chennai')
School.create(name:'P.S. Higher Secondary School',location:'Mylapore',city:'chennai')
School.create(name:'Padma Seshadri Bala Bhavan Schools',location:'Nungambakkam, K.K. Nagar, Siruseri',city:'chennai')
School.create(name:'The PSBB Millennium School',location:'GST Road, Gerugambakkam',city:'chennai')
School.create(name:'Sethu Bhaskara Matriculation Higher Secondary School',location:'Ambattur',city:'chennai')
School.create(name:'RPC Matriculation Higher Secondary School',location:'Thiruvottiyur',city:'chennai')
School.create(name:'Our Ladys Matriculation Higher Secondary School',location:'Thiruvottiyur',city:'chennai')
School.create(name:'Sishya School',location:'Adyar',city:'chennai')
School.create(name:'St. Bedes Anglo Indian Higher Secondary School',location:'Santhome',city:'chennai')
School.create(name:'St. Johns Matriculation Higher Secondary School',location:'Alwarthirunagar',city:'chennai')
School.create(name:'St. Josephs Anglo-Indian Higher Secondary School',location:'Perambur',city:'chennai')
School.create(name:'St. Kevins Anglo Indian High School',location:'Royapuram',city:'chennai')
School.create(name:'St. Columbans Girls Anglo-Indian Higher Secondary School',location:'Parrys Corner',city:'chennai')
School.create(name:'St. Marys Anglo-Indian Higher Secondary School',location:'Parrys Corner',city:'chennai')
School.create(name:'St. Matthias Anglo Indian Higher Secondary School',location:'Vepery',city:'chennai')
School.create(name:'St. Patricks Anglo Indian Higher Secondary School',location:'Adyar',city:'chennai')
School.create(name:'St. Theresas Girls Higher Secondary School',location:'Pallavaram',city:'chennai')
School.create(name:'Sundravalli Memorial School',location:'Chromepet',city:'chennai')
School.create(name:'The Hindu Higher Secondary School',location:'Triplicane',city:'chennai')
School.create(name:'Unity Public School',location:'Kotturpuram',city:'chennai')
School.create(name:'IIT Madras',location:'Aided by IIT-Madras',city:'chennai')
School.create(name:'Vani Vidyalaya Senior Secondary & Junior College',location:'West K.K. Nagar',city:'chennai')
School.create(name:'Vellayan Chettiyar Higher Secondary School',location:'Tiruvottiyur',city:'chennai')
School.create(name:'Vidya Mandir Senior Secondary School',location:'Mylapore',city:'chennai')
School.create(name:'Vyasa Vidyalaya Matriculation Higher Secondary School',location:'Adambakkam',city:'chennai')
School.create(name:'Wesley Higher Secondary School',location:'Royapettah',city:'chennai')
School.create(name:'Gill Adarsh Matriculation Higher Secondary School',location:'Royapettah',city:'chennai')
School.create(name:'Hindu Senior Secondary School',location:'Indira Nagar',city:'chennai')
School.create(name:'M. C. C. Higher Secondary School',location:'Chetput',city:'chennai')
School.create(name:'P.S. Senior Secondary School',location:'Mylapore',city:'chennai')
School.create(name:'RMK Residential School',location:'Kavaraipettai',city:'chennai')
School.create(name:'Saraswathi Vidyalaya Senior Secondary School',location:'Vadapalani',city:'chennai')
School.create(name:'SBOA School & Junior College',location:'Anna Nagar',city:'chennai')
School.create(name:'Sharanalaya Montessori School',location:'Nungambakkam',city:'chennai')
School.create(name:'Siragu Montessori School',location:'Avadi',city:'chennai')
School.create(name:'Sri Chaithanya',location:'Manapakkam',city:'chennai')
School.create(name:'Sri Sankara Senior Secondary School',location:'Adyar',city:'chennai')
School.create(name:'V. Ramakrishna Polytechnic',location:'Thiruvottiyur',city:'chennai')
School.create(name:'UV Global Pre School',location:'Selaiyur',city:'chennai')
School.create(name:'Valliammal Matriculation Higher Secondary School',location:'',city:'chennai')
School.create(name:'Model Matriculation Higher Secondary School',location:'5, Thandavaraya Mudali Street, Chennai, Tamil Nadu 600021',city:'chennai')
School.create(name:'Smart Minds Academy',location:'54&56, Brindavan street extension, West Mambalam, Chennai-600033',city:'chennai')
